#!/usr/bin/python3
import sys

def factorize(value):
    i = 2
    if value < 2:
        return
    while value % i:
        i += 1
    print("{:.0f}={:.0f}*{:.0f}".format(value, value / i, i))

if len(sys.argv) != 2:
    exit()

try:
    with open(sys.argv[1]) as f:
        for line in f:
            value = int(line.strip())
            factorize(value)
except:
    pass
