#!/usr/bin/python3
import sys

def is_prime(n):

    if n < 2:
        return False

    for i in range(2, int(n**0.5)+1):
        if n % i == 0:
            return False

    return True

def factorize(n):
    for i in range(2, n):
        if n % i == 0 and is_prime(i) and is_prime(n//i):
            print("{}={}*{}".format(n, (n // i), i))
            return

def main():
    with open(sys.argv[1], 'r') as f:
        n = int(f.readline().strip())
        factorize(n)

if __name__ == '__main__':
    main()
